
AWSTemplateFormatVersion: '2010-09-09'
Description: This is master cloudformation template for core Practera DB infrastructure
  design

Metadata:
  Authors:
    Description: Sunil and Mihai (sunil@practera.com/mihai@practera.com) based on
      AWS quickstart/widdix and best practise.
  License:
    Description: Copyright 2020 Intersective PTY LTD and its affiliates. All Rights
      Reserved.

Parameters:

  CFNS3BucketName:
    Description: S3 bucket name for the Cloudformation template stored. This string
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Default: devops-cfn-templates
    Type: String
  CFNS3BucketRegion:
    Default: ap-southeast-2
    Description: The AWS Region where the Cloudformation template stored in S3 bucket
      is hosted. When using your own bucket, you must specify this value.
    Type: String
  StackName:
    ConstraintDescription: This will be unique string to represent our stack.
    Default: beta
    Description: A client/project/product unique name for the stack to idnetify later.
      This string can include numbers, lowercase letters, uppercase letters, and hyphens
      (-). It cannot start or end with a hyphen (-).
    Type: String
    AllowedValues: [au,us,uk,p2,lf,nu,alpha,beta,shared]
  Env:
    Description: Environment type.
    Default: stage
    Type: String
    AllowedValues:
      - sandbox
      - stage
      - live
    ConstraintDescription: must specify sandbox,stage,live.
  RedisEngineVersion:
    Description: 'Redis version'
    Type: String
    Default: '6.x'
    AllowedValues: # aws elasticache describe-cache-engine-versions --engine redis --query "CacheEngineVersions[].EngineVersion"
    - '3.2.6' # 3.2.4 and 3.2.10 do not support encryption
    - '4.0.10'
    - '5.0.0'
    - '5.0.3'
    - '5.0.4'
    - '5.0.5'
    - '5.0.6'
    - '6.x'
  CacheNodeType:
    Description: 'The compute and memory capacity of the nodes in the node group (shard).'
    Type: 'String'
    Default: 'cache.t2.micro'
  TransitEncryption:
    Description: 'Enable encryption for data in transit? (see https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html)'
    Type: 'String'
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  AuthToken:
    Description: 'Optional password (16 to 128 characters) used to authenticate against Redis (requires TransitEncryption := true; leave blank to disable password-protection).'
    Type: 'String'
    Default: ''
    MaxLength: 128
    NoEcho: true
  SnapshotRetentionLimit:
    Description: 'The number of days for which ElastiCache retains automatic snapshots before deleting them (set to 0 to disable backups).'
    Type: Number
    Default: 35
    MinValue: 0
    MaxValue: 35
  SnapshotName:
    Description: 'Optional name of a snapshot from which you want to restore (leave blank to create an empty cache).'
    Type: 'String'
    Default: ''
  SubDomainName:
    Description: 'Name that is used to create the DNS entry §{SubDomainName}.§{HostedZoneName} (required when ParentZoneStack is set, otherwise not considered)'
    Type: String
    Default: redis
  NumShards:
    Description: 'Number of shards in the cluster.'
    Type: 'Number'
    Default: 1
    MinValue: 1
    MaxValue: 250
  NumReplicas:
    Description: 'Number of replicas per shard.'
    Type: 'Number'
    Default: 1
    MinValue: 0
    MaxValue: 5
  CPUUtilizationThreshold:
    Description: 'The maximum percentage of CPU usage (set to -1 to disable).'
    Type: Number
    Default: 80
    MinValue: -1
    MaxValue: 100
  DatabaseMemoryUsagePercentageThreshold:
    Description: 'The maximum percentage of memory usage (set to -1 to disable).'
    Type: Number
    Default: 90
    MinValue: -1
    MaxValue: 100
  DBSnapshotIdentifier:
    Description: 'Optional identifier for the DB cluster snapshot from which you want to restore (leave blank to create an empty cluster).'
    Type: String
    Default: ''
  DBBackupRetentionPeriod:
    Description: 'The number of days to keep snapshots of the cluster.'
    Type: Number
    MinValue: 1
    MaxValue: 35
    Default: 30
  DBSecretARN:
    AllowedPattern: arn:aws:secretsmanager:.*
    ConstraintDescription: Only valid secret manager ARN allowed
    Description: 'The DB secret ARN to retrieve from secret manager'
    Type: String
    NoEcho: true
  SubDomainNameWithDot:
    Description: 'Name that is used to create the DNS entry with trailing dot, e.g. §{SubDomainNameWithDot}§{HostedZoneName}. Leave blank for naked (or apex and bare) domain. Requires ParentZoneStack parameter!'
    Type: String
    Default: 'aurora.'
  ServerlessSubDomainNameWithDot:
    Description: 'Name that is used to create the DNS entry with trailing dot, e.g. §{SubDomainNameWithDot}§{HostedZoneName}. Leave blank for naked (or apex and bare) domain. Requires ParentZoneStack parameter!'
    Type: String
    Default: 'aurora-serverless.'
  PreferredBackupWindow:
    Description: 'IGNORED BECAUSE OF A BUG IN CLOUDFORMATION! VALUE WILL APPLY IN THE FUTURE! The daily time range in UTC during which you want to create automated backups.' # TODO remove uppercase warning
    Type: String
    Default: '09:54-10:24'
  PreferredMaintenanceWindow:
    Description: 'IGNORED BECAUSE OF A BUG IN CLOUDFORMATION! VALUE WILL APPLY IN THE FUTURE! The weekly time range (in UTC) during which system maintenance can occur.' # TODO remove uppercase warning
    Type: String
    Default: 'sat:07:00-sat:07:30'
  EnableDataApi:
    Description: 'Enable the Data API (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html).'
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
  AutoPause:
    Description: 'Enable automatic pause for a Serverless Aurora cluster. A cluster can be paused only when it has no connections. If a cluster is paused for more than seven days, the cluster might be backed up with a snapshot. In this case, the cluster is restored when there is a request to connect to it.'
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
  MaxCapacity:
    Description: 'The maximum capacity units for a Serverless Aurora cluster.'
    Type: String
    AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
    Default: 2
  MinCapacity:
    Description: 'The minimum capacity units for a Serverless Aurora cluster.'
    Type: String
    AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
    Default: 2
  SecondsUntilAutoPause:
    Description: 'The time, in seconds, before a Serverless Aurora cluster is paused.'
    Type: Number
    MinValue: 1
    MaxValue: 86400
    Default: 300
  AuroraServerlessEngineVersion:
    Description: 'Aurora Serverless PostgreSQL version.'
    Type: String
    Default: '10.7'
    AllowedValues: ['10.7','10.12'] 
    # aws rds describe-db-engine-versions --engine aurora-postgresql --query 'DBEngineVersions[?contains(SupportedEngineModes,`serverless`)]'
  AuroraRDSEngineVersion:
    Description: 'Aurora engine and version'
    Type: String
    AllowedValues:
    - 'aurora-postgresql-10.7' # aws rds describe-db-engine-versions --engine aurora-postgresql --query 'DBEngineVersions[?contains(SupportedEngineModes,`provisioned`)].EngineVersion'
    - 'aurora-postgresql-12.4'
    Default: aurora-postgresql-10.7
  RDSEngineVersion:
    Description: 'PostgreSQL version.'
    Type: String
    Default: '9.6.5'
    AllowedValues: ['9.5.2', '9.5.4', '9.5.6', '9.5.7', '9.5.9', '9.5.10', '9.5.12', '9.5.13', '9.5.14', '9.5.15', '9.5.16', '9.5.18', '9.5.19', '9.5.20', '9.5.21', '9.5.22', '9.5.23', '9.6.1', '9.6.2', '9.6.3', '9.6.5', '9.6.6', '9.6.8', '9.6.9', '9.6.10', '9.6.11', '9.6.12', '9.6.14', '9.6.15', '9.6.16', '9.6.17', '9.6.18', '9.6.19', '10.1', '10.3', '10.4', '10.5', '10.6', '10.7', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '11.1', '11.2', '11.4', '11.5', '11.6', '11.7', '11.8', '11.9', '12.2', '12.3', '12.4'] # aws rds describe-db-engine-versions --engine postgres --query "DBEngineVersions[].EngineVersion"
  DBInstanceClass:
    Description: 'The instance type of database server (see https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.DBInstanceClass.html).'
    Type: String
    Default: 'db.t2.small'
  ISRDSServerless:
    Description: 'True if we want Aurora RDS Serverless.'
    Type: String
    Default: true
    AllowedValues:
    - true
    - false
    - "RDS"
  DBAllocatedStorage:
    Description: 'The allocated storage size, specified in GB (ignored when DBSnapshotIdentifier is set, value used from snapshot).'
    Type: Number
    Default: 5
    MinValue: 5
    MaxValue: 16384
  RDSDBInstanceClass:
    Description: 'The instance type of database server.'
    Type: String
    Default: 'db.t2.micro'

Conditions:
  RDSServerless: !Equals
      - !Ref 'ISRDSServerless'
      - 'true'
  NonRDSServerless: !Equals
      - !Ref 'ISRDSServerless'
      - 'false'
  RDSInstance: !Equals
      - !Ref 'ISRDSServerless'
      - 'RDS'

Resources:

  # RedisStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub 'https://${CFNS3BucketName}.s3.${CFNS3BucketRegion}.amazonaws.com/${StackName}/${CFNS3BucketRegion}/cfn-templates/redis.yml'
  #     Parameters:
  #       StackName: !Ref 'StackName'
  #       Env: !Ref 'Env'
  #       EngineVersion: !Ref 'RedisEngineVersion'
  #       CacheNodeType: !Ref 'CacheNodeType'
  #       TransitEncryption: !Ref 'TransitEncryption'
  #       AuthToken: !Ref 'AuthToken'
  #       SnapshotRetentionLimit: !Ref 'SnapshotRetentionLimit'
  #       SnapshotName: !Ref 'SnapshotName'
  #       SubDomainName: !Ref 'SubDomainName'
  #       NumShards: !Ref 'NumShards'
  #       NumReplicas: !Ref 'NumReplicas'
  #       CPUUtilizationThreshold: !Ref 'CPUUtilizationThreshold'
  #       DatabaseMemoryUsagePercentageThreshold: !Ref 'DatabaseMemoryUsagePercentageThreshold'

  AuroraServerlessPostgresStack:
    Condition: RDSServerless
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CFNS3BucketName}.s3.${CFNS3BucketRegion}.amazonaws.com/${StackName}/${CFNS3BucketRegion}/cfn-templates/aurora-serverless-postgres.yml'
      Parameters:
        StackName: !Ref 'StackName'
        Env: !Ref 'Env'
        DBSnapshotIdentifier: !Ref 'DBSnapshotIdentifier'
        DBBackupRetentionPeriod: !Ref 'DBBackupRetentionPeriod'
        SubDomainNameWithDot: !Ref 'ServerlessSubDomainNameWithDot'
        EnableDataApi: !Ref 'EnableDataApi'
        AutoPause: !Ref 'AutoPause'
        MaxCapacity: !Ref 'MaxCapacity'
        MinCapacity: !Ref 'MinCapacity'
        SecondsUntilAutoPause: !Ref 'SecondsUntilAutoPause'
        EngineVersion: !Ref 'AuroraServerlessEngineVersion'
        DBSecretARN: !Ref 'DBSecretARN'

  AuroraPostgresStack:
    Condition: NonRDSServerless
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CFNS3BucketName}.s3.${CFNS3BucketRegion}.amazonaws.com/${StackName}/${CFNS3BucketRegion}/cfn-templates/aurora-postgres.yml'
      Parameters:
        StackName: !Ref 'StackName'
        Env: !Ref 'Env'
        DBSnapshotIdentifier: !Ref 'DBSnapshotIdentifier'
        DBBackupRetentionPeriod: !Ref 'DBBackupRetentionPeriod'
        SubDomainNameWithDot: !Ref 'SubDomainNameWithDot'
        Engine: !Ref 'AuroraRDSEngineVersion'
        DBInstanceClass: !Ref DBInstanceClass
        DBSecretARN: !Ref 'DBSecretARN'

        
  RDSPostgresStack:
    Condition: RDSInstance
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CFNS3BucketName}.s3.${CFNS3BucketRegion}.amazonaws.com/${StackName}/${CFNS3BucketRegion}/cfn-templates/rds-postgres.yml'
      Parameters:
        StackName: !Ref StackName
        Env: !Ref Env
        DBAllocatedStorage: !Ref DBAllocatedStorage
        DBInstanceClass: !Ref RDSDBInstanceClass
        DBSnapshotIdentifier: !Ref 'DBSnapshotIdentifier'
        DBBackupRetentionPeriod: !Ref 'DBBackupRetentionPeriod'
        SubDomainNameWithDot: !Ref 'SubDomainNameWithDot'
        EngineVersion: !Ref 'RDSEngineVersion'
        DBSecretARN: !Ref 'DBSecretARN'